name: CI

on:
  push:
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute the Python script create-update-file.py
        run: python ./create-update-file.py

      - name: List files
        run: |
          ls -R

      - name: Commit latest build
        uses: EndBug/add-and-commit@v7
        with:
          add: 'my-test'


