name: Deploy PR

on:
  workflow_run:
    workflows: ["Validate PR"]
    types:
      - completed
  #pull_request_target:
  #  branches:
  #    - main
  #  paths:
  #    - 'submit.txt'

jobs:
  deploy:
    name: Add new items from submit.txt
    #needs: check
    #if: needs.check.outputs.run_job == 'true'
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      #- uses: actions/download-artifact@v2
      #  with:
      #    name: pr
      #    path: pr

      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      - run: unzip pr.zip


      - name: Display structure of downloaded files
        run: ls -R






    #steps:
    #  - name: Checkout
    #    uses: actions/checkout@v2
    #  #  with:
    #  #    ref: ${{ github.head_ref }}

    #  - name: Set up Python
    #    uses: actions/setup-python@v2
    #    with:
    #      python-version: 3.8
    #  - name: Install dependencies
    #    run: |
    #      python -m pip install --upgrade pip
    #      pip install pytest
    #      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    #  - name: build new base.txt
    #    run: python ./script.py

    #  - name: test new build with pytest
    #    if: ${{ success() }}
    #    run: |
    #      pytest test.py

    #  - name: Save latest upate
    #    run: |
    #      mkdir -p ./pr
    #      cat base.txt > ./pr/NR
    #  - uses: actions/upload-artifact@v2
    #    with:
    #      name: pr
    #      path: pr/


    #- name: Commit latest build
    #  if: ${{ success() }}
    #  uses: EndBug/add-and-commit@v7
    #  with:
    #    add: '.'
      #    push: origin main
      #- name: Commit latest build
      #  if: ${{ success() }}
      #  uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
      #    push_options: '--force'

      #- name: Automerge successful build
      #  if: ${{ success() }}
      #  uses: alexwilson/enable-github-automerge-action@main
      #  with:
      #    github-token: "${{ secrets.GITHUB_TOKEN }}"

