name: deploy

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: build new base.txt
        run: python ./script.py

      - name: test new build with pytest
        if: ${{ success() }}
        run: |
          pytest test.py

      - name: Commit latest build
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v7
        with:
          add: '.'

      - name: Automerge successful build
        if: ${{ success() }}
        uses: alexwilson/enable-github-automerge-action@main
          github-token: "${{ secrets.GITHUB_TOKEN }}"

