name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' #every 5 minutes
  workflow_distpatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          gitub_token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: main
