name: test

on:
  push:
    paths-ignore: 
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute the Python script create-update-file.py
        run: python ./create-update-file.py

      - name: List files
        run: |
          ls -R

